SELECT o.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM ANIMAL_OUTS o 
WHERE o.ANIMAL_ID in 
(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact %'
) and not SEX_UPON_OUTCOME LIKE 'Intact %';
