SELECT ID, NAME, PLACES.HOST_ID 
FROM PLACES ,(
    SELECT COUNT(*) AS PLACE_CNT,HOST_ID 
    FROM PLACES
    GROUP BY HOST_ID 
    ORDER BY HOST_ID 
) AS c
WHERE PLACE_CNT>=2 AND PLACES.HOST_ID = c.HOST_ID;